### ISSUE TITLE
Bug: Prompt gets deleted after submission

### ISSUE THREAD

**Issue by nx10** [childmindresearch/agate#20]
### Description

In the image generation tab the prompt text in the textbox gets deleted after pressing [submit], this makes it a bit annoying to finetune prompts.

### Steps to Reproduce

- write prompt
- press submit
- look at screen

### Expected Results

The old prompt is there for editing

### Actual Results

The prompt is not there for editing

**Comment by ReinderVosDeWael** [comment]
Huh I'd actually purposefully built this in because I assumed this would be the behavior users want ;D

**Comment by nx10** [comment]
Maybe I'm just bad at coming up with prompts but I always need to refine it once or twice :D
