### ISSUE TITLE
Bug: Large messages break chatbot

### ISSUE THREAD

**Issue by nx10** [childmindresearch/agate#28]
### Description

Sending a large message makes the chatbot stop responding to messages

### Steps to Reproduce

Send large message

### Expected Results

The bot answers, and continues to respond to subsequent messages

### Actual Results

It does not

@ReinderVosDeWael edits:

Associated tasks:

- [ ] Automatically count number of tokens for long messages.
- [ ] If number of tokens is equal to or more than the limit (128,000) minus 4096, discard the oldest message(s) until this is no longer true.
- [ ] Warn the user this happened.
- [ ] Send the data.

**Comment by ReinderVosDeWael** [comment]
Model has been updated to GPT-4 Turbo to make this less of an issue in the short term. 

For very long inputs (should make some shorthand based on total number of character), we're going to have to start counting tokens and either warning the user if it is too long and/or discarding the oldest messages.

**Comment by ReinderVosDeWael** [comment]
No longer needed due to the implementation of docbot.
